# Generated by Django 2.2.1 on 2020-03-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share_json',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='城市名称')),
                ('cityid', models.CharField(max_length=15, verbose_name='城市编码')),
                ('value', models.IntegerField(verbose_name='显示数值')),
                ('usersYD', models.IntegerField(verbose_name='移动用户数')),
                ('usersDX', models.IntegerField(verbose_name='电信用户数')),
                ('usersLT', models.IntegerField(verbose_name='联通用户数')),
                ('shareYD', models.IntegerField(verbose_name='移动份额')),
                ('shareDX', models.IntegerField(verbose_name='电信份额')),
                ('shareLT', models.IntegerField(verbose_name='联通份额')),
            ],
            options={
                'verbose_name': '份额数据',
                'verbose_name_plural': '份额数据',
            },
        ),
    ]
