# Generated by Django 2.2.1 on 2020-03-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='xiaoqu_aoi_json',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField(verbose_name='PID')),
                ('gaode_lng', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='高德经度')),
                ('gaode_lat', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='高德纬度')),
                ('google_lng', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='谷歌经度')),
                ('google_lat', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='谷歌纬度')),
                ('baidu_lng', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='百度经度')),
                ('baidu_lat', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='百度纬度')),
            ],
            options={
                'verbose_name': '小区边界',
                'verbose_name_plural': '小区边界',
            },
        ),
    ]
