# Generated by Django 2.2.1 on 2020-03-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_xiaoqu_aoi_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiaoqu_aoi_json',
            name='p_id',
            field=models.CharField(max_length=16, verbose_name='PID'),
        ),
    ]
