# Generated by Django 2.2.1 on 2020-03-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200308_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='xiaoqu_poi_json',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=16, verbose_name='PID')),
                ('aoi_name', models.CharField(max_length=128, verbose_name='小区名称')),
                ('type_name', models.CharField(max_length=128, verbose_name='小区类型')),
                ('type_code', models.IntegerField(verbose_name='类型编码')),
                ('addr', models.CharField(max_length=128, verbose_name='小区地址')),
                ('tel', models.CharField(max_length=128, verbose_name='联系电话')),
                ('gaode_lng', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='高德经度')),
                ('gaode_lat', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='高德纬度')),
                ('google_lng', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='谷歌经度')),
                ('google_lat', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='谷歌纬度')),
                ('baidu_lng', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='百度经度')),
                ('baidu_lat', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='百度纬度')),
                ('province_name', models.CharField(max_length=32, verbose_name='省份名称')),
                ('city_code', models.IntegerField(verbose_name='城市代码')),
                ('city_name', models.CharField(max_length=32, verbose_name='城市名称')),
                ('towns_code', models.IntegerField(verbose_name='区域代码')),
                ('towns_name', models.CharField(max_length=32, verbose_name='区域名称')),
            ],
            options={
                'verbose_name': '小区信息',
                'verbose_name_plural': '小区信息',
            },
        ),
    ]
